### PR TITLE
Adds support for DEL CHECK and VERSION

### LINKED ISSUE #15: Plugin doesn't handle "remove" requests
It is in some sense fine that it doesn't handle remove requests, but because it crashes when handed anything other than an allocation request, it is quite likely that IP deallocation of other networks is broken when this plugin is used by multus.

### PR DESCRIPTION
**Pull request by pboothe**
All in the hopes of preventing resource leaks due to (previously) crashing when given a DEL

Fixes #15 

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/index2ip/16)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/index2ip/16)* status: 0 of 1 LGTMs obtained

___
*[main.go, line 256 at r1](https://reviewable.io/reviews/m-lab/index2ip/16#-MMX92kw12L3M2XjnY5W:-MMX92kw12L3M2XjnY5X:b-hgtr2m) ([raw file](https://github.com/m-lab/index2ip/blob/84c3fc9961319eef3d07a1401ad8cbe2b550399b/main.go#L256)):*
> ```Go
> 		return args[1], nil
> 	default:
> 		log.Printf("Unknown CNI operation: %q\n", args[1])
> ```

The return paths are identical. It looks redundant with the one in main. Can this be simplified?
___
*[main.go, line 276 at r1](https://reviewable.io/reviews/m-lab/index2ip/16#-MMX9kWFDxaJZMZIrqgw:-MMX9kWFDxaJZMZIrqgx:bwmeust) ([raw file](https://github.com/m-lab/index2ip/blob/84c3fc9961319eef3d07a1401ad8cbe2b550399b/main.go#L276)):*
> ```Go
> 	os.Stdout.Write([]byte(`{
>   "cniVersion": "0.2.0",
>   "supportedVersions": [ "0.2.0" ]
> ```

Please add a note that this should correspond to the configuration in https://github.com/m-lab/k8s-support/blob/master/k8s/networks/networks.jsonnet#L56 (or similar).

**Review by pboothe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/index2ip/16)* status: 0 of 1 LGTMs obtained

___
*[main.go, line 256 at r1](https://reviewable.io/reviews/m-lab/index2ip/16#-MMX92kw12L3M2XjnY5W:-MMXLyjPB302veZ3GF0U:b-896fix) ([raw file](https://github.com/m-lab/index2ip/blob/84c3fc9961319eef3d07a1401ad8cbe2b550399b/main.go#L256)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The return paths are identical. It looks redundant with the one in main. Can this be simplified?
</blockquote></details>

Done.
___
*[main.go, line 276 at r1](https://reviewable.io/reviews/m-lab/index2ip/16#-MMX9kWFDxaJZMZIrqgw:-MMXMCbk3mFG0nvEMcNr:b-896fix) ([raw file](https://github.com/m-lab/index2ip/blob/84c3fc9961319eef3d07a1401ad8cbe2b550399b/main.go#L276)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add a note that this should correspond to the configuration in https://github.com/m-lab/k8s-support/blob/master/k8s/networks/networks.jsonnet#L56 (or similar).
</blockquote></details>

Done.

**Review by pboothe — COMMENTED** [review]
PTAL

> *[Reviewable](https://reviewable.io/reviews/m-lab/index2ip/16#-:-MMXMZQN7ZOY6HiTqVng:bb71pro)* status: 0 of 1 LGTMs obtained

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: -- what are the steps to get this into the production system?

> *[Reviewable](https://reviewable.io/reviews/m-lab/index2ip/16#-:-MMXNJG7-yfhKRWkGcxF:b-68xjqy)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by pboothe** [comment]
It will get rolled into epoxy-images the next time we rebuild our images - https://github.com/m-lab/epoxy-images/blob/b23d5548052547089a2088be68007d7d2d21778c/setup_stage3_ubuntu.sh#L219

Looking at that shell script, I am now sucking air through my teeth about whether I think that deployment pattern is a good one. I don't know what a better one would be, though.

**Pull request merged**
